### ISSUE TITLE
When put null value into cache, java.lang.NullPointerException got thrown

### ISSUE THREAD

**Issue by NKU915** [mybatis/caffeine-cache#152]
Putting a null value into the caffeine cache caused a NullPointerException, the root cause it Caffeine doesn't accept null value.

```java
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.put(UnboundedLocalCache.java:372)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.put(UnboundedLocalCache.java:367)
	at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:130)
	at org.mybatis.caches.caffeine.CaffeineCache.putObject(CaffeineCache.java:57)
	at [=============hidden==========].cache.CacheDelegator.putObject(CacheDelegator.java:42)
	at org.apache.ibatis.cache.decorators.LoggingCache.putObject(LoggingCache.java:49)
	at org.apache.ibatis.cache.decorators.TransactionalCache.flushPendingEntries(TransactionalCache.java:120)
	at org.apache.ibatis.cache.decorators.TransactionalCache.commit(TransactionalCache.java:99)
	at org.apache.ibatis.cache.TransactionalCacheManager.commit(TransactionalCacheManager.java:45)
	at org.apache.ibatis.executor.CachingExecutor.commit(CachingExecutor.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy119.commit(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at tansun.creditx.audit.DataChangeInterceptor.intercept(DataChangeInterceptor.java:94)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy119.commit(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:220)
```
where TransactionalCache.java:120 is:
```
  private void flushPendingEntries() {
    for (Map.Entry<Object, Object> entry : entriesToAddOnCommit.entrySet()) {
      delegate.putObject(entry.getKey(), entry.getValue());
    }
    for (Object entry : entriesMissedInCache) {
      if (!entriesToAddOnCommit.containsKey(entry)) {
        delegate.putObject(entry, null);     <============================                    
      }
    }
  }
```

**Comment by hazendaz** [comment]
@NKU915 What version of caffeine cache are you using?  Has issue been raised with caffeine cache?  Is this something special here you think we should be fixing?  I mean its null, if they don't accept null, not sure what you want us to do.  Thinking version which you can override could help and further maybe if discussed at caffeine that may help.  I can help do what you think is needed in any regard but need a bit more info here.

**Comment by ben-manes** [comment]
Caffeine does not support null keys or values. That is often simulated using a sentinel, like `Optional<V>`, which avoids confusion between (absent mapping vs null value). This mirrors `ConcurrentHashMap`.

In its current form, I don't think this adapter is providing users a benefit. The constructor forces the MyBatis cache to be unconfigured, where internally an `UnboundedLocalCache` is a thin adapter to `ConcurrentHashMap`. Presumably you wanted a cache with a configuration like size eviction (internally a `BoundedLocalCace`), but do not provide a means to let users configure that. The `Caffeine` builder does not itself specify a file format as the prefered configuration scheme can differ across projects, and `CaffeineSpec` can be helpful for convenience. If MyBatis wants each vendor to own its own custom configuration scheme, then the JCache (jsr107) might be preferable. That would work fine here, though please note that this spec was rejected by JEE and Jakarta on multiple occasions, abandoned, and is fairly awful. However, it would be fine for cases like this.

Thanks a lot for providing support.
